# Generated by Django 4.1.2 on 2022-11-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vission',
            field=models.TextField(default='test vission'),
            preserve_default=False,
        ),
    ]
